title: Tan Yong Jie
logo: /assets/img/Profile.jpeg
description: **Robotics Systems Undergraduate at Singapore Institute of Technology**  
WorldSkills Mechatronics Competitor | Autonomous Navigation with ROS1
show_downloads: true
theme: jekyll-theme-minimal
